version: "3"
services:
  exchange-db:
    container_name: exchange-db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    networks: [exchange]
    volumes:
      - exchange-db-data:/var/lib/postgresql/data

networks:
  exchange:
    external:
      name: exchange_net

volumes:
  exchange-db-data:
    driver: local