CREATE TABLE "WALLET"."CURRENCIES" (
    "CODE" VARCHAR(15) PRIMARY KEY,
    "NAME" VARCHAR(63) NOT NULL,
    "NUMBER" SMALLINT NOT NULL,
    "MIN_UNITS" SMALLINT NOT NULL
);
INSERT INTO "WALLET"."CURRENCIES"("CODE", "NAME", "NUMBER", "MIN_UNITS")
VALUES ('AZN', 'Azerbaijan Manat', 944, 2),
    ('USD', 'US Dollar', 840, 2),
    ('EUR', 'Euro', 978, 2);
CREATE SEQUENCE "WALLET"."WALLETS_ID_SEQ" AS BIGINT INCREMENT BY 1;
CREATE TABLE "WALLET"."WALLETS" (
    "ID" BIGINT PRIMARY KEY,
    "ACCOUNT_ID" BIGINT NOT NULL,
    "BALANCE" BIGINT NOT NULL,
    "CURRENCY_CODE" VARCHAR(15) NOT NULL,
    "STATUS" SMALLINT NOT NULL,
    "VERSION" VARCHAR(63) NOT NULL,
    "CREATED_DATE" BIGINT NOT NULL,
    "LAST_UPDATE_DATE" BIGINT
);
ALTER TABLE "WALLET"."WALLETS"
ADD CONSTRAINT "FK_WALLETS_CURRENCY_CODE" FOREIGN KEY ("CURRENCY_CODE") REFERENCES "WALLET"."CURRENCIES"("CODE");
CREATE INDEX "WALLETS_ACCOUNT_ID_IDX" on "WALLET"."WALLETS" ("ACCOUNT_ID");
CREATE INDEX "WALLETS_VERSION_IDX" on "WALLET"."WALLETS" ("VERSION");
CREATE INDEX "WALLETS_STATUS_IDX" on "WALLET"."WALLETS" ("STATUS");
CREATE SEQUENCE "WALLET"."WALLET_TRANSACTIONS_ID_SEQ" AS BIGINT INCREMENT BY 1;
CREATE TABLE "WALLET"."WALLET_TRANSACTIONS" (
    "ID" BIGINT PRIMARY KEY,
    "WALLET_ID" BIGINT NOT NULL,
    "REFERENCE_ID" VARCHAR(255),
    "TYPE" SMALLINT NOT NULL,
    "STATUS" SMALLINT NOT NULL,
    "VERSION" VARCHAR(63) NOT NULL,
    "AMOUNT" BIGINT NOT NULL,
    "CURRENCY_CODE" VARCHAR(15) NOT NULL,
    "CREATED_DATE" BIGINT NOT NULL,
    "LAST_UPDATE_DATE" BIGINT
);
ALTER TABLE "WALLET"."WALLET_TRANSACTIONS"
ADD CONSTRAINT "FK_WALLET_TRANSACTIONS_CURRENCY_CODE" FOREIGN KEY ("CURRENCY_CODE") REFERENCES "WALLET"."CURRENCIES"("CODE");
ALTER TABLE "WALLET"."WALLET_TRANSACTIONS"
ADD CONSTRAINT "FK_WALLET_TRANSACTIONS_WALLET_ID" FOREIGN KEY ("WALLET_ID") REFERENCES "WALLET"."WALLETS"("ID");
CREATE INDEX "WALLET_TRANSACTIONS_REF_ID_IDX" on "WALLET"."WALLET_TRANSACTIONS" ("REFERENCE_ID");
CREATE INDEX "WALLET_TRANSACTIONS_STATUS_IDX" on "WALLET"."WALLET_TRANSACTIONS" ("STATUS");
CREATE INDEX "WALLET_TRANSACTIONS_VERSION_IDX" on "WALLET"."WALLET_TRANSACTIONS" ("VERSION");
CREATE UNIQUE INDEX "WALLET_TRANSACTIONS_WALLET_REF_IDX" on "WALLET"."WALLET_TRANSACTIONS" ("REFERENCE_ID", "REFERENCE_ID");
CREATE SEQUENCE "WALLET"."WALLET_OPERATIONS_ID_SEQ" AS BIGINT INCREMENT BY 1;
CREATE TABLE "WALLET"."WALLET_OPERATIONS" (
    "ID" BIGINT PRIMARY KEY,
    "WALLET_ID" BIGINT NOT NULL,
    "TRANSACTION_ID" BIGINT,
    "TYPE" SMALLINT NOT NULL,
    "CREATED_DATE" BIGINT NOT NULL
);
ALTER TABLE "WALLET"."WALLET_OPERATIONS"
ADD CONSTRAINT "FK_WALLET_OPERATIONS_WALLET_ID" FOREIGN KEY ("WALLET_ID") REFERENCES "WALLET"."WALLETS"("ID");
ALTER TABLE "WALLET"."WALLET_OPERATIONS"
ADD CONSTRAINT "FK_WALLET_OPERATIONS_TRANSACTION_ID" FOREIGN KEY ("TRANSACTION_ID") REFERENCES "WALLET"."WALLET_TRANSACTIONS"("ID");
CREATE TABLE "WALLET"."WALLET_OPERATION_VALUES" (
    "WALLET_OPERATION_ID" BIGINT NOT NULL,
    "KEY" VARCHAR(255) NOT NULL,
    "VALUE" VARCHAR(255),
    PRIMARY KEY ("WALLET_OPERATION_ID", "KEY")
);
ALTER TABLE "WALLET"."WALLET_OPERATION_VALUES"
ADD CONSTRAINT "FK_WALLET_OPERATION_VALUES_OPERATION_ID" FOREIGN KEY ("WALLET_OPERATION_ID") REFERENCES "WALLET"."WALLET_OPERATIONS"("ID");
CREATE INDEX "WALLET_OPERATION_VALUES_OPERATION_ID_IDX" on "WALLET"."WALLET_OPERATION_VALUES" ("WALLET_OPERATION_ID");