version: "3"
services:
  exchange_db:
    container_name: exchange_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    networks: [exchange]
    volumes:
      - exchange_db_data:/var/lib/postgresql/data

networks:
  exchange:
    external:
      name: exchange_net

volumes:
  exchange_db_data:
    driver: local