CREATE SEQUENCE "ACCOUNT"."ACCOUNT_ID_SEQ" AS BIGINT INCREMENT BY 1;

CREATE TABLE "ACCOUNT"."ACCOUNTS"
(
    "ID" BIGINT PRIMARY KEY,
    "USERNAME" VARCHAR(127) NOT NULL ,
    "EMAIL" VARCHAR(127),
    "PASSWORD" VARCHAR(63) NOT NULL ,
    "STATUS" SMALLINT NOT NULL,
    "ACTIVATION_CODE" VARCHAR(63),
    "CREATED_DATE" BIGINT NOT NULL,
    "LAST_UPDATE_DATE" BIGINT
);

